### ISSUE TITLE
Can't login after install Let's chat : Whoops There were problems logging you in.

### ISSUE THREAD

**Issue by ashwin2011** [sdelements/lets-chat#607]
Spec :

Ubuntu 14.04 64bit
node v0.10.25
mongodb v 3.0.6
python 2.7.5-5ubuntu3

I got the following errors :

$ npm install
npm http GET https://registry.npmjs.org/passport
npm http 304 https://registry.npmjs.org/passport
npm http GET https://registry.npmjs.org/passport-strategy
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http 304 https://registry.npmjs.org/passport-strategy
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm ERR! peerinvalid The package passport does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer passport.socketio@3.6.1 wants passport@~0.3.0

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /opt/chat/lets-chat
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/chat/lets-chat/npm-debug.log
npm ERR! not ok code 0

I did the following :

npm install passport@~0.3.0 and npm install passport.socketio@3.6.1

npm start

It works :

> lets-chat@0.4.2 prestart /opt/chat/lets-chat
> migroose

> lets-chat@0.4.2 start /opt/chat/lets-chat
> node app.js

██╗     ███████╗████████╗███████╗     ██████╗██╗  ██╗ █████╗ ████████╗
██║     ██╔════╝╚══██╔══╝██╔════╝    ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
██║     █████╗     ██║   ███████╗    ██║     ███████║███████║   ██║  
██║     ██╔══╝     ██║   ╚════██║    ██║     ██╔══██║██╔══██║   ██║  
███████╗███████╗   ██║   ███████║    ╚██████╗██║  ██║██║  ██║   ██║  
╚══════╝╚══════╝   ╚═╝   ╚══════╝     ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝

Release 0.4.2

I successfully create an account but I can't login.

I have the following message :

 Whoops There were problems logging you in.

I think there is a problem with the cookie management.

Below is the console of chrome : 

POST http://111.11.111.11:5000/account/login 400 (Bad Request)jQuery.ajaxTransport.options.send @ jquery.js:8625jQuery.extend.ajax @ jquery.js:8161onSubmit @ login.js:7handle @ jquery.validate.js:65(anonymous function) @ jquery.validate.js:85jQuery.event.dispatch @ jquery.js:4430jQuery.event.add.elemData.handle @ jquery.js:4116
Navigated to http://111.11.111.11:5000/login
gingerEditor.min.js:21 Running Ginger Widget  version 0.1.0.585
jquery.js:8625 POST http://111.11.111.11:5000/account/login 400 (Bad Request)jQuery.ajaxTransport.options.send @ jquery.js:8625jQuery.extend.ajax @ jquery.js:8161onSubmit @ login.js:7handle @ jquery.validate.js:65(anonymous function) @ jquery.validate.js:85jQuery.event.dispatch @ jquery.js:4430jQuery.event.add.elemData.handle @ jquery.js:4116
Navigated to http://111.11.111.11:5000/login
gingerEditor.min.js:21 Running Ginger Widget  version 0.1.0.585
jquery.js:8625 POST http://111.11.111.11:5000/account/login 400 (Bad Request)jQuery.ajaxTransport.options.send @ jquery.js:8625jQuery.extend.ajax @ jquery.js:8161onSubmit @ login.js:7handle @ jquery.validate.js:65(anonymous function) @ jquery.validate.js:85jQuery.event.dispatch @ jquery.js:4430jQuery.event.add.elemData.handle @ jquery.js:4116

Any fix ?

**Comment by antoinealb** [comment]
I had the same issue, I don't have a fix either :( Ubuntu 14.04 here

**Comment by ashwin2011** [comment]
I have test it on Debian also and have the same problem. Any fix guys ?

**Comment by antoinealb** [comment]
I was able to make it work by running npm install on `0.3.0` then upgrading to `0.4.2`. Maybe you try it too?

**Comment by ashwin2011** [comment]
Hi thanks for the tips but I still get this error on installing the modules  (npm install ): 

 ^
../deps/libexpat/lib/xmltok.c:186:21: note: ‘isName2’ declared here
   int (PTRFASTCALL *isName2)(const ENCODING *, const char *);
                     ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  SOLINK_MODULE(target) Release/obj.target/node_expat.node: Finished
  COPY Release/node_expat.node
make: Leaving directory '/opt/chat/lets-chat-0.3.0/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/build'
npm ERR! peerinvalid The package passport does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer passport.socketio@3.6.1 wants passport@~0.3.0

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /opt/chat/lets-chat-0.3.0
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/chat/lets-chat-0.3.0/npm-debug.log
npm ERR! not ok code 0

**Comment by ashwin2011** [comment]
After a long struggle, I finally made it worked :

Here is the instructions :

#get the latest version
git clone https://github.com/sdelements/lets-chat.git

#enter the folder
cd lets-chat/

#update the modules
npm install

#Fix the passport module
npm install passport.socketio@3.5.1 --save

#launch the application
npm start

It has worked for me.

**Comment by saranrapjs** [comment]
I'm also seeing an issue with logging in, as of recent changes.  Specifically, in a window with no pre-existing session (e.g. no cookies) login will be unsuccessful, despite the user having been properly registered.  

I'm finding that by more or less undoing this commit https://github.com/sdelements/lets-chat/commit/28ed9bc8e8ace5d21a05abfa7f9ec0e5453c8891, e.g. setting `passport-http` to `0.3.0` and `passport.socketio` to `3.5.1` and re-installing dependencies (`npm install`), login works as expected.  Presumably some kind of dependency issue is at play?

**Comment by Rubikan** [comment]
saranrapjs made a small typo as it seems, you need to set `<passport.socketio>` to 3.6.1, 3.5.1 is the version that is used now in the not working version.

**Comment by ashwin2011** [comment]
Yea when i shifted from 3.6.1 to 3.5.1 everything worked.

**Comment by saranrapjs** [comment]
Oops, typo corrected :)

**Comment by jangrewe** [comment]
Confirmed!
```
npm install passport-http@0.3.0 --save
npm install passport.socketio@3.6.1 --save
```
fixed it.

**Comment by apsolut** [comment]
@jangrewe  thanks :+1:

**Comment by vext01** [comment]
Same here on a local OpenBSD install. @jangrewe's suggestion fixes this.

**Comment by lucker6666** [comment]
Seems the latest docker image still have this problem even the package.json was "fixed" to 3.6.1

from previous comments @ashwin2011 and @jangrewe i am really confused for passport.socketio which version should be used?

**Comment by sibartlett** [comment]
The dependency versions for passport and passport.socketio should now be truly fixed. There was some confusion, and weirdness when I was testing these changes. I apologize that it's taken us too long to fix these issues.
